name = "sphinx-aether-api"
account_id = "74b94b7ffc15701b77e53f81bea03813"
main = "src/index.js"
compatibility_date = "2025-12-09"

[vars]
BACKEND_URL = "https://voyagers-api.aetherintelligence.net"

[observability]
enabled = true
